### ISSUE TITLE
add advertisement

### ISSUE THREAD

**Issue by mkw5950** [triangular-opensource/Taiyo#1]
Sequence - 
Buy/Sell
Category -> Product ->Description->Dimension/Size*->Specification->Quantity->Location-(where material is required/available)>Price expected ->Bid (default for 15 days or party's acceptance whichever is earlier).-> attachment photo/file.

*Dimension/Size = (Thickness or Diameter - Three digits + two decimal points, Width & Length - Four digits max) 

Coating in GSM is applicable only for products in coated category. I will provide the product wise feature dynamics.

**Comment by savagecarol** [comment]
resolved
